module: Fluxor
author: Morten Bjerg Gregersen
github_url: https://github.com/FluxorOrg/Fluxor
copyright: '© 2021 under [open source license](https://github.com/FluxorOrg/Fluxor/blob/master/LICENSE).'
swift_version: 5.2

documentation: "Documentation/Guides/*.md"
abstract: "Documentation/Abstracts/*.md"

custom_categories:
  - name: Guides
    children:
    - Testing Reducers
    - Testing Selectors
    - Testing Effects
  - name: Store
    children:
    - Store
  - name: Actions
    children:
    - Action
    - ActionTemplate
    - AnonymousAction
    - IdentifiableAction
  - name: Reducers
    children:
    - Reducer
    - ReduceOn
  - name: Selectors
    children:
    - SelectorProtocol
    - Selector
    - Selector1
    - Selector2
    - Selector3
    - Selector4
    - Selector5
  - name: Effects
    children:
    - Effects
    - Effect
  - name: Extensions
    children:
    - Publisher
  - name: Debugging
    children:
    - Interceptor
    - PrintInterceptor
  - name: Using Fluxor with SwiftUI
    children:
    - StoreValue
    - ObservableValue
    - StorePropertyWrapper
    - StorePropertyWrapperError
  - name: Test Support
    children:
    - MockStore
    - EffectRunner
    - TestInterceptor
