name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  coverage:
    name: Generate test coverage
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v --enable-code-coverage
    - name: Export coverage
      run: xcrun llvm-cov export -format="lcov" -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" .build/x86_64-apple-macosx/debug/FluxorPackageTests.xctest/Contents/MacOS/FluxorPackageTests > coverage.lcov
    - name: Upload coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: ls
        coverageLocations: coverage.lcov:lcov
        debug: true
  build-and-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.1", "5.2", "5.3", "5.4"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift
      uses: fwal/setup-swift@v1.7.0
      with:
          swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
