name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v --enable-code-coverage
    - name: Install slather
      run: gem install slather
    - name: Upload coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: e658ce73b71169fa83b630cca94f8e1c4252243575add58d28533fb5dba1a7a8
      with:
        coverageCommand: slather coverage -s
        coverageLocations: .build/debug/codecov/Fluxor.json
        debug: true
