name: Docs

on:
  push:
    branches:
    - master

jobs:
  pages:
    name: Documentation for Pages
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation for Pages
        uses: sersoft-gmbh/swifty-docs-action@v1
      - name: Add CNAME
        run: echo -n fluxor.dev > docs/CNAME
      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: "docs"
        env:
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  wiki:
    name: Documentation for Wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation for Wiki
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          format: "commonmark"
          module-name: Fluxor
          output: "Documentation-Wiki"
      - name: Upload to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation-Wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
