name: Docs

on:
  push:
    branches:
    - docs

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: Fluxor
          output: "Documentation"
      - name: Upload to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.4.1
        with:
          build_dir: "./.build/documentation"
