name: Docs

on:
  push:
    branches:
    - master

jobs:
  pages:
    name: Documentation for Pages
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sourcekitten
        run: brew install sourcekitten
      - name: Generate Documentation for Pages
        run: ./Documentation/generate_docs.sh
      - name: Add CNAME
        run: echo -n fluxor.dev > docs/CNAME
      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: "docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
