name: Test

on:  
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v --enable-code-coverage
    - name: Codecov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: $CODECOV_TOKEN
